# homelab-media-docker-stack
#
# Services
#   Portainer   - Manage containers
#   Watchtower  - Container Updating
#   Heimdall    - Docker Dashboard
#   Plex Server - Plex Media Server
#   Tautilli    - Plex Server Monitor
#   Ombi        - Plex Requests

version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: unless-stopped
    command: --templates http://templates/templates.json
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIG_DIR}/portainer/data:/data
      - ${CONFIG_DIR}/shared:/shared
    ports:
      - "9000:9000"
    environment:
      - TZ=${TZ}
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/heimdall:/config
    ports:
      - "8081:80"
      - "8082:443"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  plexms:
    image: plexinc/pms-docker:plexpass
    container_name: plexms
    restart: unless-stopped
    volumes:
      - ${MEDIA_DIR}:/media
      - ${CONFIG_DIR}/plexms:/config
      - ${CONFIG_DIR}/shared:/shared
      - /tmp/transcode:/transcode
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      - TZ=${TZ}
      - HOSTNAME="plex-ms"
      - PLEX_CLAIM=${CLAIM}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
      - ADVERTISE_IP=http://10.0.10.53:32400/
  tautulli:
    image: linuxserver/tautulli
    container_name: tautulli
    restart: unless-stopped
    depends_on:
      - plexms
    volumes:
      - ${CONFIG_DIR}/tautulli/config:/config
      - ${CONFIG_DIR}/tautulli/logs:/logs:ro
      - ${CONFIG_DIR}/shared:/shared
    ports:
      - "8181:8181"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    restart: unless-stopped
    depends_on:
      - plexms
    volumes:
      - ${CONFIG_DIR}/ombi:/config
    ports:
      - "3579:3579"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
